[package]
name = "shorty"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rusqlite = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
