[package]
name = "shorty"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rusqlite = { workspace = true }
url = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true, features = ["alloc"] }

[lints]
workspace = true
